name: first

on: [push, pull_request]

jobs:
  job1:
    name: j1
    runs-on: ubuntu-latest
    steps:
    - name: step one
      uses: actions/checkout@v2
    - name: step two
      run: env | sort
  job2:
    name: j2
    runs-on: windows-latest
    steps:
    - name: step 1
      uses: actions/checkout@v2
    - name: step 2
      run: "Get-ChildItem Env: | Sort-Object Name"
