# This is a basic workflow to help you get started with Actions

name: TAGGING

on:
  create:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    env:
      REF: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: create_branch_from_tag
        run: |
          empty=""
          initial="refs/tags/"
          tagName=${REF/$initial/$empty}
          git checkout -b $tagName-QA 
          git push --set-upstream origin $tagName-QA
          
          git checkout -b $tagName-PROD
          git push --set-upstream origin $tagName-PROD
          echo "============="
          echo "FINISHED"
